CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_LOG=y
CONFIG_SPAGHETTI_APP_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_CORE_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_DRIVER_REGISTRY_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_MODULE_MANAGER_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_DISCOVERY_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_CONFIG_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_STORAGE_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_DATA_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_RUNTIME_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_COMMUNICATION_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_MQTT_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_WIFI_PROFILES_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_INA219_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_RELAY_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_MAX_MODULES=8
CONFIG_SPAGHETTI_INA219_MAX_INSTANCES=4
CONFIG_SPAGHETTI_RELAY_MAX_INSTANCES=4
CONFIG_SPAGHETTI_RUNTIME_STACK_SIZE=1536
CONFIG_SPAGHETTI_RUNTIME_PRIORITY=4
CONFIG_SPAGHETTI_RUNTIME_RULE_STACK_SIZE=1536
CONFIG_SPAGHETTI_RUNTIME_RULE_PRIORITY=4
CONFIG_SPAGHETTI_RUNTIME_STOP_TIMEOUT_MS=1000
CONFIG_SPAGHETTI_MQTT_QUEUE_DEPTH=4
CONFIG_SPAGHETTI_MQTT_WORKER_STACK_SIZE=4096
CONFIG_SPAGHETTI_MQTT_ADAPTER_STACK_SIZE=1536
CONFIG_SPAGHETTI_MQTT_PRIORITY=5
CONFIG_SPAGHETTI_MQTT_STOP_TIMEOUT_MS=2000
CONFIG_SPAGHETTI_WIFI_PROFILE_MAX_COUNT=4
CONFIG_SPAGHETTI_WIFI_PROFILE_AUTO_CONNECT=y
CONFIG_SPAGHETTI_WIFI_PROFILE_WORKER_STACK_SIZE=4096
CONFIG_SPAGHETTI_WIFI_PROFILE_WORKER_PRIORITY=5
CONFIG_SPAGHETTI_WIFI_SCAN_TIMEOUT_SECONDS=15
CONFIG_SPAGHETTI_WIFI_CONNECT_TIMEOUT_SECONDS=30
CONFIG_SPAGHETTI_WIFI_DISCONNECT_TIMEOUT_SECONDS=5
CONFIG_SPAGHETTI_WIFI_RETRY_SECONDS=30
CONFIG_SPAGHETTI_WIFI_PASSWORD_INPUT_TIMEOUT_SECONDS=60
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_BOOTLOADER_NO_DOWNGRADE=y
CONFIG_NVS=y
CONFIG_NVS_DATA_CRC=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_SECURE_STORAGE=y
CONFIG_SECURE_STORAGE_ITS_IMPLEMENTATION_ZEPHYR=y
CONFIG_SECURE_STORAGE_ITS_STORE_IMPLEMENTATION_SETTINGS=y
CONFIG_SECURE_STORAGE_ITS_MAX_DATA_SIZE=128
CONFIG_SECURE_STORAGE_ITS_TRANSFORM_IMPLEMENTATION_AEAD=y
CONFIG_SECURE_STORAGE_ITS_TRANSFORM_AEAD_SCHEME_AES_GCM=y
CONFIG_SECURE_STORAGE_ITS_TRANSFORM_AEAD_KEY_PROVIDER_DEVICE_ID_HASH=y
CONFIG_SECURE_STORAGE_ITS_TRANSFORM_AEAD_NONCE_PROVIDER_DEFAULT=y
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_PSA_CRYPTO_C=y
CONFIG_HWINFO=y
CONFIG_ZCBOR=y
CONFIG_NETWORKING=y
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_DHCPV4=y
CONFIG_DNS_RESOLVER=y
CONFIG_MQTT_LIB=y
CONFIG_ZBUS=y
CONFIG_ZBUS_MSG_SUBSCRIBER=y
CONFIG_ZBUS_PREFER_DYNAMIC_ALLOCATION=n
CONFIG_ZBUS_MSG_SUBSCRIBER_BUF_ALLOC_STATIC=y
CONFIG_ZBUS_MSG_SUBSCRIBER_NET_BUF_POOL_SIZE=8
CONFIG_ZBUS_MSG_SUBSCRIBER_NET_BUF_STATIC_DATA_SIZE=64
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_CMD_BUFF_SIZE=600
CONFIG_SHELL_STACK_SIZE=4096
CONFIG_NET_L2_WIFI_SHELL=y
