CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_SPAGHETTI_APP_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_CORE_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_DRIVER_REGISTRY_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_MODULE_MANAGER_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_CONFIG_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_STORAGE_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_INA219_LOG_LEVEL_INF=y
CONFIG_SPAGHETTI_MAX_MODULES=8
CONFIG_SPAGHETTI_INA219_MAX_INSTANCES=4
CONFIG_I2C=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_NVS_DATA_CRC=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
