import 'package:dashboard_domain/dashboard_domain.dart';

import 'exposure_manifest.dart';

ExposureManifest demoExposureManifest() {
  return const ExposureManifest(
    manifestId: 'casa-demo',
    bindings: [
      ExposureBinding(
        pointId: 'salotto.temperatura',
        label: 'Temperatura salotto',
        sourceKey: 1,
        schemaId: 'env.temperature',
        fieldId: 1,
        valueType: ValueType.number,
        visualHint: VisualHint.gauge,
        unit: '°C',
        initialValue: 21.4,
      ),
      ExposureBinding(
        pointId: 'giardino.pompa',
        label: 'Pompa giardino',
        kind: 'actuator',
        sourceKey: 2,
        schemaId: 'act.pump',
        fieldId: 1,
        valueType: ValueType.boolean,
        visualHint: VisualHint.animated,
        visualStates: ['idle', 'running'],
        writable: true,
        initialValue: false,
      ),
      ExposureBinding(
        pointId: 'giardino.umidita',
        label: 'Umidità vaso',
        sourceKey: 3,
        schemaId: 'env.humidity',
        fieldId: 1,
        valueType: ValueType.number,
        visualHint: VisualHint.value,
        unit: '%',
        initialValue: 47,
      ),
      ExposureBinding(
        pointId: 'ingresso.luce',
        label: 'Luce ingresso',
        kind: 'actuator',
        sourceKey: 4,
        schemaId: 'act.light',
        fieldId: 1,
        valueType: ValueType.boolean,
        visualHint: VisualHint.toggle,
        writable: true,
        initialValue: true,
      ),
      ExposureBinding(
        pointId: 'cucina.consumo',
        label: 'Consumo cucina',
        sourceKey: 5,
        schemaId: 'pwr.power',
        fieldId: 1,
        valueType: ValueType.number,
        visualHint: VisualHint.sparkline,
        unit: 'W',
        initialValue: 182,
      ),
      ExposureBinding(
        pointId: 'cantina.allarme',
        label: 'Allarme cantina',
        sourceKey: 6,
        schemaId: 'evt.alarm',
        fieldId: 1,
        valueType: ValueType.boolean,
        visualHint: VisualHint.status,
        visualStates: ['ok', 'alarm'],
        initialValue: false,
      ),
      ExposureBinding(
        pointId: 'serra.irrigazione',
        label: 'Irrigazione',
        kind: 'actuator',
        sourceKey: 7,
        schemaId: 'act.valve',
        fieldId: 1,
        valueType: ValueType.boolean,
        visualHint: VisualHint.button,
        writable: true,
        initialValue: false,
      ),
      ExposureBinding(
        pointId: 'esterno.luminosita',
        label: 'Luminosità',
        sourceKey: 8,
        schemaId: 'env.lux',
        fieldId: 1,
        valueType: ValueType.number,
        visualHint: VisualHint.gauge,
        unit: 'lux',
        initialValue: 340,
      ),
    ],
  );
}
