import type { ProcessingCatalogEntry, ProcessingNodeKind, ProcessingRuntime } from "./types.js";

function nodeKindFromRuntime(runtime: ProcessingRuntime): ProcessingNodeKind | undefined {
  switch (runtime) {
    case "core-block":
      return "block";
    case "core-rule":
      return "rule";
    case "core-schedule":
      return "schedule";
    case "core-event":
      return "event-source";
    default:
      return undefined;
  }
}

function e(entry: Omit<ProcessingCatalogEntry, "nodeKind">): ProcessingCatalogEntry {
  return { ...entry, nodeKind: nodeKindFromRuntime(entry.runtime) };
}

/**
 * AppBlocks Library operations that have a SpaghettiLAB analog, plus native
 * Block Drivers. Features-tab items stay `feature` until that dump arrives.
 * Vendor-only hardware is omitted, not listed as a fake Core driver.
 */
export const PROCESSING_BLOCK_CATALOG: readonly ProcessingCatalogEntry[] = [
  e({
    id: "native.schedule",
    label: "Schedule",
    subtitle: "Campionamento periodico",
    category: "trigger",
    runtime: "core-schedule",
    availability: "shipped",
    notes: "struct spaghetti_runtime_schedule_config: period_ms su un Module. Equivalente AppBlocks: On Time Period.",
  }),
  e({
    id: "native.event-source",
    label: "Event source",
    subtitle: "Record asincroni",
    category: "trigger",
    runtime: "core-event",
    availability: "shipped",
    notes: "Module che pubblica eventi (`spaghetti_module_manager_start_events`), non uno schedule.",
  }),
  e({
    id: "appblocks.system",
    label: "On Boot",
    subtitle: "All'avvio del Core",
    category: "system",
    runtime: "feature",
    availability: "unavailable",
    appblocksId: "system",
    notes: "Non è un Block del grafo: arriverà con le Features (evento di boot), non con un type_id inventato.",
  }),
  e({
    id: "appblocks.debug",
    label: "Debug Print",
    subtitle: "Log di debug",
    category: "system",
    runtime: "feature",
    availability: "unavailable",
    appblocksId: "debug",
    notes: "In AppBlocks è una Feature (nome + intervallo di stampa). Si integra quando arriva il dump Features.",
  }),
  e({
    id: "appblocks.label",
    label: "Comment",
    subtitle: "Nota di authoring",
    category: "system",
    runtime: "authoring",
    availability: "unavailable",
    appblocksId: "label",
    notes: "Non entra nel Config: usa il campo Nome sull'Inspector del nodo.",
  }),
  e({
    id: "appblocks.system_reboot",
    label: "Reboot",
    subtitle: "Riavvio Core",
    category: "system",
    runtime: "core-admin",
    availability: "unavailable",
    appblocksId: "system_reboot",
    notes: "Operazione amministrativa (S094), non un nodo del Device Processing Graph.",
  }),
  e({
    id: "appblocks.upgrade_firmware",
    label: "Firmware Upgrade",
    subtitle: "OTA",
    category: "system",
    runtime: "core-admin",
    availability: "unavailable",
    appblocksId: "upgrade_firmware",
    notes: "Capability Marketplace / OTA (S103), non un Block di elaborazione.",
  }),

  e({
    id: "appblocks.variable_changed",
    label: "On Variable Changed",
    subtitle: "Cambio variabile",
    category: "variables",
    runtime: "feature",
    availability: "unavailable",
    appblocksId: "variable_changed",
    notes: "Il Core non ha uno store di variabili generiche: i dati sono record/field. Features.",
  }),
  e({
    id: "appblocks.variable_set",
    label: "Variable Set/Math",
    subtitle: "Scrivi variabile",
    category: "variables",
    runtime: "feature",
    availability: "unavailable",
    appblocksId: "variable_set",
    notes: "Stesso confine: niente RAM variabili illimitata sul Core. Features o un Block field già catalogato.",
  }),

  e({
    id: "appblocks.command_triggered",
    label: "On Command",
    subtitle: "Evento comando",
    category: "logic",
    runtime: "core-event",
    availability: "shipped",
    appblocksId: "command_triggered",
    notes: "Event source sul Module che espone il comando: il firmware non ha un nodo 'On Command' separato.",
  }),
  e({
    id: "appblocks.comparison",
    label: "IF Condition",
    subtitle: "Soglia booleana",
    category: "logic",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "comparison",
    typeId: "threshold",
    notes: "Il grafo Core è un DAG, non un flowchart if/else: `threshold` emette un bool da collegare a Rule/publish.",
  }),
  e({
    id: "appblocks.compound_condition",
    label: "IF Compound Condition",
    subtitle: "Più soglie",
    category: "logic",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "compound_condition",
    typeId: "compound_threshold",
    notes: "Oggi si compongono più Block `threshold`. Un driver composto arriverà come type_id `compound_threshold`.",
  }),
  e({
    id: "appblocks.switch",
    label: "Switch",
    subtitle: "Seleziona un ingresso",
    category: "logic",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "switch",
    typeId: "select",
    notes: "Block firmware `select`.",
  }),
  e({
    id: "appblocks.forloop",
    label: "For-Next Loop",
    subtitle: "Iterazione",
    category: "logic",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "forloop",
    notes: "Il processing graph è aciclico e bounded: un for-next illimitato non può girare sul Core.",
  }),
  e({
    id: "appblocks.command_trigger",
    label: "Execute Command",
    subtitle: "Comando su Module",
    category: "logic",
    runtime: "core-rule",
    availability: "shipped",
    appblocksId: "command_trigger",
    typeId: "threshold",
    notes: "Rule `threshold` con `commandTarget` (Module + commandId), non un Block con output.",
  }),

  e({
    id: "appblocks.arithmetic",
    label: "Calculate",
    subtitle: "Addizione (cambia type_id per − × ÷)",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "arithmetic",
    typeId: "add",
    notes: "Firmware: `add`, `subtract`, `multiply`, `divide` come Block distinti. Questo posto crea `add`; gli altri sono in palette.",
  }),
  e({
    id: "block.subtract",
    label: "Subtract",
    subtitle: "a − b",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "subtract",
    notes: "Block firmware `subtract`.",
  }),
  e({
    id: "block.multiply",
    label: "Multiply",
    subtitle: "a × b",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "multiply",
    notes: "Block firmware `multiply`.",
  }),
  e({
    id: "block.divide",
    label: "Divide",
    subtitle: "a ÷ b",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "divide",
    notes: "Block firmware `divide`. Overflow/divisione per zero = errore bounded, non NaN silenzioso.",
  }),
  e({
    id: "appblocks.bitwise",
    label: "Bitwise",
    subtitle: "Mask e shift",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "bitwise",
    typeId: "mask_shift",
    notes: "Block firmware `mask_shift`.",
  }),
  e({
    id: "appblocks.math_compound",
    label: "Custom Function",
    subtitle: "Polinomio bounded",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "math_compound",
    typeId: "polynomial",
    notes: "Non è codice arbitrario: sul Core è il Block `polynomial` (grado e coefficienti bounded).",
  }),
  e({
    id: "appblocks.random",
    label: "Random",
    subtitle: "Valore casuale",
    category: "math",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "random",
    typeId: "random",
    notes: "Driver `random` ancora da scrivere; il grafo si può già autorare con questo type_id.",
  }),
  e({
    id: "block.scale_offset",
    label: "Scale / offset",
    subtitle: "in × scale + offset",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "scale_offset",
    notes: "Block firmware nativo, senza gemello AppBlocks.",
  }),
  e({
    id: "block.clamp",
    label: "Clamp",
    subtitle: "Satura in [min, max]",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "clamp",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.map_range",
    label: "Map range",
    subtitle: "Rimappa un intervallo",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "map_range",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.unit_convert",
    label: "Unit convert",
    subtitle: "Conversione unità",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "unit_convert",
    notes: "Block firmware nativo. Le conversioni restano nodi espliciti, mai implicite sull'edge.",
  }),
  e({
    id: "block.combine_fields",
    label: "Combine fields",
    subtitle: "Unisci campi",
    category: "math",
    runtime: "core-block",
    availability: "shipped",
    typeId: "combine_fields",
    notes: "Block firmware nativo.",
  }),

  e({
    id: "block.moving_average",
    label: "Moving average",
    subtitle: "Media mobile",
    category: "filter",
    runtime: "core-block",
    availability: "shipped",
    typeId: "moving_average",
    notes: "Block firmware nativo (pack processing-basic).",
  }),
  e({
    id: "block.low_pass",
    label: "Low pass",
    subtitle: "Passa-basso",
    category: "filter",
    runtime: "core-block",
    availability: "shipped",
    typeId: "low_pass",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.median",
    label: "Median",
    subtitle: "Filtro mediano",
    category: "filter",
    runtime: "core-block",
    availability: "shipped",
    typeId: "median",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.hysteresis",
    label: "Hysteresis",
    subtitle: "Soglia con isteresi",
    category: "filter",
    runtime: "core-block",
    availability: "shipped",
    typeId: "hysteresis",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.debounce",
    label: "Debounce",
    subtitle: "Antirimbalzo",
    category: "filter",
    runtime: "core-block",
    availability: "shipped",
    typeId: "debounce",
    notes: "Block firmware nativo.",
  }),
  e({
    id: "block.kalman",
    label: "Kalman",
    subtitle: "Filtro 1D",
    category: "filter",
    runtime: "core-block",
    availability: "pack",
    typeId: "kalman",
    packId: "processing-kalman",
    notes: "Capability Pack `processing-kalman`, non nell'immagine minima.",
  }),

  e({
    id: "appblocks.timer_completed",
    label: "On Timer Completed",
    subtitle: "Timer scaduto",
    category: "time",
    runtime: "feature",
    availability: "unavailable",
    appblocksId: "timer_completed",
    notes: "Oggetti timer AppBlocks sono Features, non lo Schedule firmware (period_ms su un Module).",
  }),
  e({
    id: "appblocks.time_interval",
    label: "On Time Period",
    subtitle: "Campionamento periodico",
    category: "time",
    runtime: "core-schedule",
    availability: "shipped",
    appblocksId: "time_interval",
    notes: "Schedule firmware: `period_ms` legato a un Module. Nessun cron.",
  }),
  e({
    id: "appblocks.cron_event",
    label: "On Scheduled Event",
    subtitle: "Calendario / cron",
    category: "time",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "cron_event",
    notes: "Nessun cron/calendario nel Config Core. Orari calendario → System Automation (Node-RED).",
  }),
  e({
    id: "appblocks.timer_start",
    label: "Timer Start",
    subtitle: "Avvia timer",
    category: "time",
    runtime: "feature",
    availability: "unavailable",
    appblocksId: "timer_start",
    notes: "Feature timer, non Block. Per ritardi bounded nel grafo usa Delay.",
  }),
  e({
    id: "appblocks.timer_stop",
    label: "Timer Stop",
    subtitle: "Ferma timer",
    category: "time",
    runtime: "feature",
    availability: "unavailable",
    appblocksId: "timer_stop",
    notes: "Feature timer, non Block.",
  }),
  e({
    id: "appblocks.time_delay",
    label: "Delay (seconds)",
    subtitle: "Ritardo bounded",
    category: "time",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "time_delay",
    typeId: "delay",
    notes: "S071 prevede Block stateful/delay catalogati. Driver `delay` ancora da scrivere.",
  }),
  e({
    id: "appblocks.datetime",
    label: "Get Current DateTime",
    subtitle: "Orologio Core",
    category: "time",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "datetime",
    typeId: "get_datetime",
    notes: "Driver `get_datetime` pianificato; usa l'ora di sistema del Core.",
  }),
  e({
    id: "appblocks.datetime_format",
    label: "DateTime/Time Formatter",
    subtitle: "Formatta data/ora",
    category: "time",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "datetime_format",
    typeId: "datetime_format",
    notes: "Driver bounded (template fisso), non sprintf libero.",
  }),

  e({
    id: "appblocks.keypad",
    label: "On Button Pressed",
    subtitle: "Fronte pulsante",
    category: "io",
    runtime: "core-event",
    availability: "shipped",
    appblocksId: "keypad",
    notes: "Event source sul Module GPIO/pulsante del Physical Composition Graph.",
  }),
  e({
    id: "appblocks.keypad_released",
    label: "On Button Released",
    subtitle: "Rilascio pulsante",
    category: "io",
    runtime: "core-event",
    availability: "shipped",
    appblocksId: "keypad_released",
    notes: "Stesso Event source; il profilo/Module distingue press/release se li pubblica.",
  }),
  e({
    id: "appblocks.button",
    label: "On Module Button Pressed",
    subtitle: "Pulsante modulo",
    category: "io",
    runtime: "core-event",
    availability: "shipped",
    appblocksId: "button",
    notes: "Come On Button Pressed: Event source sul Module del Physical Graph.",
  }),
  e({
    id: "appblocks.button_released",
    label: "On Module Button Released",
    subtitle: "Rilascio pulsante modulo",
    category: "io",
    runtime: "core-event",
    availability: "shipped",
    appblocksId: "button_released",
    notes: "Event source sul Module.",
  }),
  e({
    id: "appblocks.interrupt",
    label: "On Interrupt",
    subtitle: "GPIO interrupt",
    category: "io",
    runtime: "core-event",
    availability: "shipped",
    appblocksId: "interrupt",
    notes: "Event source su Module GPIO che pubblica record asincroni.",
  }),
  e({
    id: "appblocks.digital_line_set",
    label: "Digital Line Set",
    subtitle: "Scrivi GPIO",
    category: "io",
    runtime: "core-rule",
    availability: "shipped",
    appblocksId: "digital_line_set",
    typeId: "threshold",
    notes: "Rule con comando sul Module GPIO, non un Block che parla con il PIN da solo.",
  }),

  e({
    id: "appblocks.num_round",
    label: "Number Round Decimal Points",
    subtitle: "Arrotonda",
    category: "strings",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "num_round",
    typeId: "round",
    notes: "Driver `round` pianificato (valore numerico bounded, non formattazione stringa libera).",
  }),

  e({
    id: "appblocks.lcd_set_screen",
    label: "LCD Set Screen",
    subtitle: "Schermo LCD",
    category: "display",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "lcd_set_screen",
    notes: "Nessun LCD sul Core. Un display è un altro Core/Module, collegato via Node-RED.",
  }),
  e({
    id: "appblocks.lcd_menu",
    label: "Enter LCD Menu",
    subtitle: "Menu LCD",
    category: "display",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "lcd_menu",
    notes: "Nessun LCD sul Core. Un display è un altro Core/Module, collegato via Node-RED.",
  }),
  e({
    id: "appblocks.lcd_text_widget",
    label: "LCD Text Widget",
    subtitle: "Testo LCD",
    category: "display",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "lcd_text_widget",
    notes: "Nessun LCD sul Core. Un display è un altro Core/Module, collegato via Node-RED.",
  }),
  e({
    id: "appblocks.lcd_image_widget",
    label: "LCD Image Widget",
    subtitle: "Immagine LCD",
    category: "display",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "lcd_image_widget",
    notes: "Nessun LCD sul Core. Un display è un altro Core/Module, collegato via Node-RED.",
  }),
  e({
    id: "appblocks.lcd_graph_widget",
    label: "LCD Line Graph Add Point",
    subtitle: "Grafico LCD",
    category: "display",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "lcd_graph_widget",
    notes: "Nessun LCD sul Core. Un display è un altro Core/Module, collegato via Node-RED.",
  }),
  e({
    id: "appblocks.lcd_graph_widget_clear",
    label: "LCD Line Graph Clear",
    subtitle: "Pulisci grafico LCD",
    category: "display",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "lcd_graph_widget_clear",
    notes: "Nessun LCD sul Core. Un display è un altro Core/Module, collegato via Node-RED.",
  }),

  e({
    id: "appblocks.pat",
    label: "LED Pattern",
    subtitle: "Comando LED",
    category: "sound",
    runtime: "core-rule",
    availability: "shipped",
    appblocksId: "pat",
    typeId: "threshold",
    notes: "Comando catalogato sul Module LED del Physical Graph.",
  }),
  e({
    id: "appblocks.beep",
    label: "Buzzer Pattern",
    subtitle: "Comando buzzer",
    category: "sound",
    runtime: "core-rule",
    availability: "shipped",
    appblocksId: "beep",
    typeId: "threshold",
    notes: "Comando catalogato sul Module buzzer.",
  }),

  e({
    id: "appblocks.table",
    label: "Table Lookup",
    subtitle: "Tabella bounded",
    category: "storage",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "table",
    typeId: "lookup_table",
    notes: "Block firmware `lookup_table` (punti bounded nel Config).",
  }),
  e({
    id: "appblocks.table_insert",
    label: "Table Insert Row",
    subtitle: "Inserisci riga",
    category: "storage",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "table_insert",
    notes: "Storage cresciuto a runtime non sta sul Core. Lookup è statico; CRUD → host/Node-RED.",
  }),
  e({
    id: "appblocks.table_update",
    label: "Table Update Row",
    subtitle: "Aggiorna riga",
    category: "storage",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "table_update",
    notes: "Niente tabelle mutabili unbounded sul Core.",
  }),
  e({
    id: "appblocks.table_delete",
    label: "Table Delete Row",
    subtitle: "Elimina riga",
    category: "storage",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "table_delete",
    notes: "Niente tabelle mutabili unbounded sul Core.",
  }),
  e({
    id: "appblocks.table_clear",
    label: "Clear Table",
    subtitle: "Svuota tabella",
    category: "storage",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "table_clear",
    notes: "Niente tabelle mutabili unbounded sul Core.",
  }),
  e({
    id: "appblocks.table_row_count",
    label: "Table Row Count",
    subtitle: "Conteggio righe",
    category: "storage",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "table_row_count",
    notes: "La lookup firmware ha dimensione fissa nel Config, non un count dinamico.",
  }),
  e({
    id: "appblocks.log_add",
    label: "Add to Event Log",
    subtitle: "Log eventi",
    category: "storage",
    runtime: "feature",
    availability: "unavailable",
    appblocksId: "log_add",
    notes: "Il Core emette già record/eventi protocollo. Un log applicativo è Feature/host.",
  }),
  e({
    id: "appblocks.settings_init",
    label: "Initialize Settings",
    subtitle: "Init impostazioni",
    category: "storage",
    runtime: "feature",
    availability: "unavailable",
    appblocksId: "settings_init",
    notes: "Il Config si applica con validate/CAS, non con un Block 'init settings'.",
  }),
  e({
    id: "appblocks.json_get_string",
    label: "JSON Get String",
    subtitle: "Estrai campo JSON",
    category: "storage",
    runtime: "core-block",
    availability: "planned",
    appblocksId: "json_get_string",
    typeId: "json_get_string",
    notes: "Solo path bounded e payload cap; JSON libero resta Node-RED.",
  }),

  e({
    id: "appblocks.ser_data_arrival",
    label: "On Serial Data Received",
    subtitle: "UART in ingresso",
    category: "serial",
    runtime: "core-event",
    availability: "shipped",
    appblocksId: "ser_data_arrival",
    notes: "Event source sul Module UART (Port o Link Module).",
  }),
  e({
    id: "appblocks.sms_recv",
    label: "On SMS Received",
    subtitle: "SMS in ingresso",
    category: "serial",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "sms_recv",
    notes: "Nessun modem SMS nel nodo minimo Core V1.",
  }),
  e({
    id: "appblocks.ser_data_send",
    label: "Serial Data Send",
    subtitle: "UART in uscita",
    category: "serial",
    runtime: "core-rule",
    availability: "shipped",
    appblocksId: "ser_data_send",
    typeId: "threshold",
    notes: "Comando sul Module UART, non un Block che apre la seriale da solo.",
  }),
  e({
    id: "appblocks.sms_send",
    label: "Send SMS",
    subtitle: "Invia SMS",
    category: "serial",
    runtime: "out-of-scope",
    availability: "unavailable",
    appblocksId: "sms_send",
    notes: "Nessun modem SMS nel nodo minimo Core V1.",
  }),

  e({
    id: "appblocks.network_changed",
    label: "On Network Changed",
    subtitle: "Cambio rete",
    category: "network",
    runtime: "feature",
    availability: "unavailable",
    appblocksId: "network_changed",
    notes: "Stato connettività è Feature/diagnostica, non un Block del grafo locale.",
  }),
  e({
    id: "appblocks.socket_data_arrival",
    label: "On Socket Data Received",
    subtitle: "Socket RX",
    category: "network",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "socket_data_arrival",
    notes: "Socket TCP/UDP verso Internet → Node-RED, non il Core bounded.",
  }),
  e({
    id: "appblocks.socket_event",
    label: "On Socket Connection Event",
    subtitle: "Socket connect/drop",
    category: "network",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "socket_event",
    notes: "System Automation Graph / Node-RED.",
  }),
  e({
    id: "appblocks.http_server_endpoint",
    label: "On HTTP Request",
    subtitle: "HTTP server",
    category: "network",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "http_server_endpoint",
    notes: "Il Core non è un HTTP server applicativo.",
  }),
  e({
    id: "appblocks.socket_connect",
    label: "Socket Connect",
    subtitle: "Apri socket",
    category: "network",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "socket_connect",
    notes: "Node-RED.",
  }),
  e({
    id: "appblocks.socket",
    label: "Socket Send",
    subtitle: "Invia su socket",
    category: "network",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "socket",
    notes: "Node-RED.",
  }),
  e({
    id: "appblocks.http",
    label: "HTTP Request",
    subtitle: "Client HTTP",
    category: "network",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "http",
    notes: "Chiamate Internet → Node-RED. Il Core pubblica su interfacce selezionate, non fa HTTP applicativo.",
  }),
  e({
    id: "appblocks.http_server_response",
    label: "HTTP Response",
    subtitle: "Risposta HTTP",
    category: "network",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "http_server_response",
    notes: "Node-RED.",
  }),

  e({
    id: "appblocks.mqtt_sub",
    label: "On MQTT Notification",
    subtitle: "MQTT in ingresso",
    category: "cloud",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "mqtt_sub",
    notes: "Ingresso MQTT applicativo fra servizi → Node-RED. Il Core ha già MQTT come trasporto protocollo, non come Block.",
  }),
  e({
    id: "appblocks.mqtt_change",
    label: "On MQTT Change",
    subtitle: "Cambio MQTT",
    category: "cloud",
    runtime: "node-red",
    availability: "unavailable",
    appblocksId: "mqtt_change",
    notes: "Node-RED / Features di connettività, non un Block.",
  }),
  e({
    id: "appblocks.mqtt_pub",
    label: "MQTT Publish",
    subtitle: "Pubblica un field",
    category: "cloud",
    runtime: "core-block",
    availability: "shipped",
    appblocksId: "mqtt_pub",
    typeId: "publish_field",
    notes: "Block `publish_field`. L'interfaccia (`core.wifi` / `core.ble` / `link.<bay>.*`) si sceglie in pubblicazione.",
  }),

  e({
    id: "appblocks.modbus_slave_register",
    label: "On Modbus Receive",
    subtitle: "Registro slave",
    category: "modbus",
    runtime: "core-event",
    availability: "pack",
    appblocksId: "modbus_slave_register",
    packId: "transport-modbus",
    notes: "Event source sul Module Modbus del pack `transport-modbus`, non un Block dedicato.",
  }),
  e({
    id: "appblocks.modbus_response",
    label: "On Modbus Response",
    subtitle: "Risposta master",
    category: "modbus",
    runtime: "core-event",
    availability: "pack",
    appblocksId: "modbus_response",
    packId: "transport-modbus",
    notes: "Evento Module del pack Modbus.",
  }),
  e({
    id: "appblocks.modbus_timeout",
    label: "On Modbus Timeout",
    subtitle: "Timeout Modbus",
    category: "modbus",
    runtime: "core-event",
    availability: "pack",
    appblocksId: "modbus_timeout",
    packId: "transport-modbus",
    notes: "Evento Module del pack Modbus.",
  }),
  e({
    id: "appblocks.modbus_write",
    label: "Modbus Request",
    subtitle: "Richiesta Modbus",
    category: "modbus",
    runtime: "core-rule",
    availability: "pack",
    appblocksId: "modbus_write",
    typeId: "threshold",
    packId: "transport-modbus",
    notes: "Comando sul Module Modbus (pack), stessa forma delle altre Rule con commandTarget.",
  }),

  e({
    id: "block.publish_field",
    label: "Publish field",
    subtitle: "Sink record",
    category: "cloud",
    runtime: "core-block",
    availability: "shipped",
    typeId: "publish_field",
    notes: "Stesso driver di MQTT Publish; voce nativa per chi cerca il type_id firmware.",
  }),
  e({
    id: "rule.threshold",
    label: "Rule soglia",
    subtitle: "Soglia → comando",
    category: "logic",
    runtime: "core-rule",
    availability: "shipped",
    typeId: "threshold",
    notes: "Rule firmware `threshold` (source field + command target). IF/Execute Command AppBlocks atterrano qui.",
  }),
];
