; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lowside
src_dir = src

[env]
extra_scripts = 
	pre:scripts/generate_nanopb_sources.py
build_flags = 
	-I../proto/generated
	-Iinclude/common
	-I$PROJECT_DIR/.pio/libdeps/$PIOENV/Nanopb

[env:lowside]
platform = raspberrypi
board = MyRP_2350B
framework = arduino
upload_port = /dev/cu.usbmodem*
upload_protocol = custom
upload_command =  /bin/bash $PROJECT_DIR/tools/build_and_flash_lowside.sh --flash-only
lib_deps = 
	askuric/Simple FOC@^2.4.0
	https://github.com/simplefoc/Arduino-FOC-drivers.git#v1.0.9
	eric-wieser/PacketIO@^0.3.0
	eric-wieser/nanopb-arduino@^1.1.0
build_flags = 
	${env.build_flags}
	-Iinclude/lowside
build_src_filter = 
	+<common/**>
	+<lowside/**>
	-<highside/**>

[env:highside]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
; Two application slots are required for UART-delivered high-side OTA.
board_build.partitions = default_16MB.csv
upload_port = /dev/cu.usbmodem*
upload_protocol = custom
upload_command =  /bin/bash $PROJECT_DIR/tools/build_and_flash_highside.sh --flash-only
lib_deps = 
	eric-wieser/PacketIO@^0.3.0
	eric-wieser/nanopb-arduino@^1.1.0
	lvgl/lvgl@8.4.0
build_flags =
	${env.build_flags}
	-Iinclude/highside
	-DLV_CONF_INCLUDE_SIMPLE
	-DBOARD_HAS_PSRAM
	-DHIGHSIDE_UART_RX_PIN=44
	-DHIGHSIDE_UART_TX_PIN=43
	-DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = 
	+<common/**>
	+<highside/**>
	-<lowside/**>
